language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - pytest --cov=AD/ADbase2
after_success:
    - bash <(curl https://codecov.io/bash) -t a79ff441-9e7b-4564-a6c9-72b1b2316c80
